spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: authservice
          uri: http://localhost:8080
          predicates:
            - Path=/server/**
          filters:
            - RewritePath=/server/(?<segment>.*), /server/api/v1/${segment}

        - id: courseservice
          uri: http://localhost:8082
          predicates:
              - Path=/courses/**
          filters:
              - RewritePath=/courses/(?<segment>.*), /courses/api/v1/${segment}

        - id: ui
          uri: http://localhost:3000
          predicates:
              - Path=/**
          filters:
            - RewritePath=/(?<segment>.*), /${segment}


      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "http://localhost:8081"
            allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "Authorization, Content-Type, Accept"
            allow-credentials: true
            max-age: 1800
  application:
    name: gateway

server:
  port: 8081

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

